language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: tutorial-cicd
  api_key:
    secure: Mrpg+hUzWM3uoygI+2g6D6voyMWvaTKlfK7mbE3FXVFvB9sSij5GnbLaf4Amavdq4eguPN42k81bWOjNRNXqZYKxO5BRdhr4Q8jjT9+ySbdYdCTN1Px9DPyXeoa8XIaQNI3PRlWi+JDlhkBe9qv9VbPcV6Vbw5bLFFBs2SfGzU1p6iOGvRXpunH/IIAWcTmjXjvTGvaETOfZqVrnYWDQG7ZSplUEdVVmTIx3MhsflFSNh4OroLdTe0w6gGa2FFI3Jj6OU3WJK9AjVCxdsorkPJZcVKoHhQDwyx7O2lF7KoHESHKeRhrmv3CqitXCn16h+Onfm9aKwDVlL/pFzvs//kvD+TMm11tisC1Zy3IrUtzHWJK/Y9XXfOUSTNHiCWtvEhWb8ofmzv8BhhUxkt+G8taNYn+o4YYOyl1j0cX8zZAvyAVF0ZLtGsolOj+dN36kyzaRiHOisb3lJz5+E93hGdy40vjN2ypbfGmBQ/P1knHMesp84eafQ4NxcuL1SHHWmgEZZ8pbCZcZXRu+KMCA7CsoBvrMH3MKGSnx7S5QqfZZWWUDH4xmqVW0WzTaOP9rlk70LAmqPdSVqb1G0043iNqtxIPi9HbyrS7UOQ954mssrszo8Iiq20b6b73E6fNRKT6Rz4FFSB6oEfhkcm8Ng4WTrZzAG6aIRUhn4lHl2Jc=
